config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-dashboard:
      branch: master
      repo: https://github.com/grycap/im-dashboard
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.byzantium_gentle_panda.sh
        container: qc.acc_gold_gracious_rhinoceros
  QC.Doc:
    repos:
      github.com/grycap/im-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_driven_roc.sh
        container: qc.doc_chartreuse_feisty_dhole
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_happy_pegasus.sh
        container: qc.doc_ginger_inventive_gibbon
      github.com/grycap/im-dashboard markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_analytical_falcon.sh
        container: qc.doc_wave_grateful_pegasus
  QC.Lic:
    repos:
      github.com/grycap/im-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.brown_mature_butterfly.sh
        container: qc.lic_ultramarine_sad_raven
  QC.Met:
    repos:
      github.com/grycap/im-dashboard validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.royal_eccentric_crocodile.sh
        container: qc.met_fandango_creative_wolf
  QC.Sec:
    repos:
      github.com/grycap/im-dashboard bandit:
        commands:
        - /usr/bin/env sh .sqa/script.mulberry_focused_lemur.sh
        container: qc.sec_violet_daring_okapi
  QC.Sty:
    repos:
      github.com/grycap/im-dashboard flake8:
        commands:
        - /usr/bin/env sh .sqa/script.orchid_plucky_chipmunk.sh
        container: qc.sty_boysenberry_bold_opossum
      github.com/grycap/im-dashboard hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.malachite_zany_anaconda.sh
        container: qc.sty_aqua_analytical_flounder
      github.com/grycap/im-dashboard jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_gentle_donkey.sh
        container: qc.sty_banana_rational_porpoise
  QC.Uni:
    repos:
      github.com/grycap/im-dashboard pytest:
        commands:
        - /usr/bin/env sh .sqa/script.maroon_quirky_ibis.sh
        container: qc.uni_raven_flexible_owl
  QC.Ver:
    repos:
      github.com/grycap/im-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_authentic_armadillo.sh
        container: qc.ver_white_proactive_eel
timeout: 5400
